limit_page: 10
max_rate_star: 5
min_rate_star: 1
positive: 0
rate_active: 1
max_rate_content: 500
product:
  conditional_max: 100
  conditional_min: 0
  limit_discount: 100
limit_discount: 100
password_email: "123456"
account_actived: 1
user:
  email:
    max_length: 255
  name_max_length: 255
  password:
    min_length: 3
shipping:
  title:
    maximum: 255
  price:
    numericality: 0
limit_record: 5
title:
  maximum: 255
price:
  numericality: 0
limit_best_seller: 10
max_length_email: 255
record_per_page: 8
rememeber_user: "1"
toastr_timeout: 350
URL_IMAGE: "/upload/"
products:
  record_per_page: 8

