limit_page: 10
user:
  email:
    max_length: 255
  name_max_length: 255
  password:
    min_length: 6
shipping:
  title:
    maximum: 255
  price:
    numericality: 0
limit_record: 5
title:
  maximum: 255
price:
  numericality: 0
record_per_page: 8
URL_IMAGE: "/upload/"
